### ISSUE TITLE
Arcadeflow theme v 15.9 : list empty and utility menu too fast 

### ISSUE THREAD

**Issue by grgohr** [zpaolo11x/Arcadeflow#29] opened 2023-04-02 20:41 UTC
hello, I wanted to try the layout (after the redraw error I downloaded the last artifact from the master actions tab so now running am+ on the last version).
after setting up 0 for cache, I see "list empty" and if i go up or down (keyboard or gamepad) it scrolls way too fast in the menus, and I cannot easily setup anything

**Comment by zpaolo11x** [comment] 2023-04-02 20:52
As far as the quick scroll is concerned, if your screen has a fast refresh rate (>60Hz) try enabling "Adjust Performance" in the "Performance & FX" menu of Arcadeflow.

Apart from the "list empty" is there something in the last run log, or on the console output?

**Comment by grgohr** [comment] 2023-04-03 06:06
thanks i'll try to reach that menu (quite a skill game at that speed ! :D)

yes it says 
AN ERROR HAS OCCURED [the index 'ps2' does not exist]

I understand Arecadeflow recognizes the systems but not that one:
though my ps2.cfg points to 
system               Sony Playstation 2

**Comment by zpaolo11x** [comment] 2023-04-03 06:41
This kind of error is usually related to some issues with the romlist. It would be useful to have the full error message (with all the debug data), a copy of your ps2.cf, attract,cfg and the ps2 romlist. If you want you can send me a direct message on discord, or on the discord helpline channel of Arcadeflow: https://discord.gg/UPtAsV5VNC

Oh, and are you maybe using a "master romlist" setup?

**Comment by grgohr** [comment] 2023-04-03 20:15
If you mean by master romlist multisystems, yes that happens for arcade (I mix several emus in one romlist file, like mame, fba, naomi, etc. but not the console ones) but I have not tested yet
I actually build mines with a custom scraper script, here are my confs:

=>attract.cfg
display	Sony Playstation 2
	layout               Sony Playstation 2(I try to change to yours)
	romlist              Sony Playstation 2

=> romlist/Sony Playstation 2.txt
#Name;Title;Emulator;CloneOf;Year;Manufacturer;Category;Players;Rotation;Control;Status;DisplayCount;DisplayType;AltRomname;AltTitle;Extra;Buttons
filename;title;ps2;;;;;0;;good;1;raster;;;;;
my 3rd column always contains the system linked to emulators/system.cfg

=> emulators/ps2.cfg
system               Sony Playstation 2

I haved tried ps2, wii and snes, all showing the same error :
AN ERROR HAS OCCURED [the index 'system' does not exist]

CALLSTACK
*FUNCTION [z_listboot()] .../zpaolo11x-Arcadeflow-4550a17/layout.nut line [6691]
relates to
if (!z_list.db1[fe.game_info(Info.Emulator, ifeindex)].rawin(fe.game_info(Info.Name, ifeindex)))

*FUNCTION [on_transition()] .../zpaolo11x-Arcadeflow-4550a17/layout.nut line [15317]
relates to 
z_listboot()

Maybe my issue is related to the difference between emulator names and display names ? (which can happen)

**Comment by zpaolo11x** [comment] 2023-04-04 05:35
I tested in the past with multi-emulator romlists and it was not a problem at all, but I'll check again to see if this has become an issue with later updates to the layout. 

If ps2 romlist only has one emulator defined, then the issue is not there, but without a complete log, with all the variable values attached, it's not possible to debug. The error says the "system" index does not exist, but I'm not sure where this "system" comes from without having a look at the variables. 

I usually ask users to share their actual romlist and config file to replicate the same case on my test rig, because every romlist and every setup is different and sometimes looking at the log can hint in the direction of which romlist is throwing an issue. Since AF reads all romlists at start, then an error in any romlist, not just the current one, can take it down.

**Comment by zpaolo11x** [comment] 2023-04-04 06:39
UPDATE: I'm not sure how multi-emulator is implemented in your case, but for AF to work correctly, at the moment, each emulator needs to have its own romlist with the roms listed. So for example if you have an emulator mame.cfg and fbneo.cfg and you created a romlist for mame.cfg, then you want to use fbneo as an emulator for some of the games, you'll have first to generate the fbneo romlist, then change the emulator in mame romlist. That will allow Arcadeflow to scan both the "mame" and "fbneo" games. I know this sounds a bit cumbersome, but at the moment AF only understand two kinds of romlists: the one generated from an emulator, and the one obtained "patching together" roms from different romlists.

**Comment by zpaolo11x** [comment] 2023-07-24 06:47
AF should be able now to cope with all mixed romlist and emulator scenarios, if you don't have any further feedback I'll close the issue...

**Closed** 2023-12-15 06:15 UTC
